In [ ]:
size = int(input())
map = [input() for i in range(size)]
nCoordenadas = int(input())

coordenadas = [map(int, input().split(",")) for i in range(nCoordenadas)]

salida = ""

for i in coordenadas:
    salida+=map[i[0]][i[1]]+"\n"

print(salida)

In [ ]:
entrada = input().split("\n")
size = int(entrada[0])
map = [entrada[1+i] for i in range(size)]
nCoordenadas = int(input())

coordenadas = [map(int, input().split(",")) for i in range(nCoordenadas)]

salida = ""

for i in coordenadas:
    salida+=map[i[0]][i[1]]+"\n"

print(salida)

In [28]:
f = open("t_values.txt", "r")
l = f.readline()
res = []
while l:
    res.append(float(l[:-1].split(" ")[1]))
    l = f.readline()
print(res)

[12200.0, 5800.0, 36800.0, 51800.0, 49200.0, 60400.0, 41000.0, 32200.0, 167200.0, 142700.0, 29100.0, 25100.0, 35200.0, 14300.0, 32200.0, 42300.0, 18500.0, 20100.0, 49200.0, 62900.0, 59200.0, 56600.0, 62100.0, 60000.0, 49500.0, 82000.0, 53100.0, 60000.0, 84700.0, 67300.0, 41500.0, 59500.0, 175100.0, 138800.0, 133400.0, 108700.0, 158700.0, 192300.0, 147000.0, 139200.0, 160500.0, 100900.0, 104400.0, 144400.0, 163200.0, 123800.0, 177000.0, 92800.0, 140200.0, 139700.0, 282900.0, 327500.0, 218200.0, 306100.0, 221500.0, 267900.0, 304500.0, 219900.0, 287100.0, 276900.0, 292500.0, 204500.0, 225500.0, 218300.0, 246800.0, 241400.0, 296900.0, 424700.0, 275400.0, 241200.0, 198900.0, 257600.0, 608500.0, 527900.0, 695500.0, 670300.0, 473800.0, 506500.0, 633700.0, 622500.0, 450700.0, 879500.0, 556300.0, 880000.0, 794600.0, 821500.0, 734400.0, 893100.0, 801200.0, 825000.0, 985300.0, 905100.0, 897200.0, 937100.0, 1042400.0, 926200.0, 725600.0, 993200.0, 1375200.0, 242500.0, 129900.0, 155400.0, 162200.0,

##**Vectores 🙄🙄🙄🙄**##

In [ ]:
vector_size = int(input())
v, w = None, None

try:
    v, w = list(map(float, input().split(" "))), list(map(float, input().split(" ")))
    if not len(v)==len(w):
        raise Exception()
except:
    print("BOBO")

s = sum(i[0]*i[1] for i in zip(v, w))
print("\n".join(map(str, [v, w, s])))

1
1 2 3
3 2 1
[1.0, 2.0, 3.0]
[3.0, 2.0, 1.0]
10.0


In [ ]:
import numpy as np

vector_size = int(input())
v, w = None, None
try:
    v, w = np.array(input().split(" "), dtype=np.float128
                    ), np.array(input().split(" "), dtype=np.float128)
    if not len(v)==len(w):
        raise Exception()
except:
    print("Error en la entrada")

s = np.dot(v, w)
print("\n".join(map(str, [v, w, s])))

1
1 2 3
3 2 1
[1. 2. 3.] [3. 2. 1.]
[1. 2. 3.]
[3. 2. 1.]
10.0


##**Media**##

In [ ]:
import random
[random.normalvariate(0, 2) for i in range(200)]

[1.9747382938545295,
 0.3224923794072399,
 1.369497269182681,
 1.496400454845087,
 -0.9607272301646015,
 1.4871663299984659,
 1.2081576607606408,
 0.2695119869497621,
 0.11796687651242133,
 0.13296024518858895,
 -2.595063167760936,
 -1.7339865880255507,
 2.8414677550767315,
 -0.2594475964516846,
 0.6234578581792336,
 -0.8937003939722594,
 0.9685055885502095,
 2.3688668567542996,
 0.15487600754503225,
 -2.618708787213924,
 0.6001126975109908,
 0.002893554411120873,
 3.5575623881748837,
 -1.1606638129662576,
 1.5519842599871632,
 2.3413184549445467,
 -3.3083811421460054,
 -1.48959275571762,
 0.015002833624081346,
 -1.1022255971310773,
 -1.4627054147846537,
 3.6854068926644707,
 -1.6132210815574768,
 -2.10832384212519,
 0.5404939706180858,
 0.7025771050526175,
 3.9184763991769764,
 0.7455394065357727,
 -3.804336642058275,
 -3.4281394832910017,
 -0.10115633122274463,
 -1.7440840157512298,
 2.864405127132938,
 -0.11699950130410149,
 3.119740494375646,
 -0.7428618579002273,
 -1.1462340692420

In [ ]:
print((lambda l: sum(l) / len(l) * 1e-9) ([float(i.split(" ")[1]) for i in open("fich.txt", "r").read().split("\n")]))

87.0378048898708
